### ISSUE TITLE
Parameter [...] is outside of the allowed domain: 0..0

### ISSUE THREAD

**Issue by ScottG489** [molexx/irdb2broadlinkha#4]
When attempting to run the following command:
```sh
./irdb2broadlinkha.bash frigidaire/WF-RG63.lircd.conf prfx_
```
I get the following errors:
```
pronto2broadlink.py found at 'irdb2broadlinkha-work/pronto2broadlink.py'.
irptransmogrifier found at 'irdb2broadlinkha-work/irptransmogrifier'.
path 'frigidaire/WF-RG63.lircd.conf' ends in .conf, assuming a lirc conf, downloading file...
downloading lirc config from 'https://sourceforge.net/p/lirc-remotes/code/ci/master/tree/remotes/frigidaire/WF-RG63.lircd.conf?format=raw' to 'irdb2broadlinkha-work/lircd.conf'...
downloaded lirc config to 'irdb2broadlinkha-work/lircd.conf'.             
converting lirc config to irp using irptransmogrifier...
irp created.                       
function: 'KEY_POWER', code: '0x10AF8877', comment: ''.
running irptransmogrifier for 'KEY_POWER', code: '0x10AF8877'...        
Parameter F = 279939191 is outside of the allowed domain: 0..0
pronto:                          
Traceback (most recent call last):
  File "irdb2broadlinkha-work/pronto2broadlink.py", line 44, in <module>
    pulses = pronto2lirc(pronto)                      
  File "irdb2broadlinkha-work/pronto2broadlink.py", line 7, in pronto2lirc
    if codes[0]:                                                                                                          
IndexError: list index out of range
BroadlinkHex:                     
writing yaml entry for 'prfx_KEY_POWER' (sanitized: 'prfx_key_power')...
'prfx_key_power':               
  friendly_name: "prfx_KEY_POWER"                                                                                         
  command_on: ''
                                   
function: 'KEY_LEFT', code: '0x10AF20DF', comment: ''.
running irptransmogrifier for 'KEY_LEFT', code: '0x10AF20DF'...       
Parameter F = 279912671 is outside of the allowed domain: 0..0
pronto:                         
Traceback (most recent call last):
  File "irdb2broadlinkha-work/pronto2broadlink.py", line 44, in <module>
    pulses = pronto2lirc(pronto)                    
  File "irdb2broadlinkha-work/pronto2broadlink.py", line 7, in pronto2lirc
    if codes[0]:                                                                                                          
IndexError: list index out of range
BroadlinkHex:                     
writing yaml entry for 'prfx_KEY_LEFT' (sanitized: 'prfx_key_left')...  
'prfx_key_left':                
  friendly_name: "prfx_KEY_LEFT"                                                                                          
  command_on: ''
                                   
function: 'KEY_UP', code: '0x10AF708F', comment: ''.

[...]

done looping around buttons.
```
With the relevant error seeming to be the title of this issue. The stdout which would redirect to a file just has a bunch of entries like this:
```yaml
'prfx_key_left':                
  friendly_name: "prfx_KEY_LEFT"                                                                                          
  command_on: ''
```

**Comment by oblivionratula** [comment]
Same problem in 2025.  Ever find a work-around?

**Comment by ScottG489** [comment]
Hard to recall, but I don't believe I ever did. I think I just went with broadlink devices that could capture and play back IR commands.
